title: Centro Desportivo de Esportes
description: Informações sobre nossos serviços e exercícios recomendados
baseurl: ""
url: "https://SEU_USUARIO.github.io/SEU_REPOSITORIO" # substitua pelo seu URL
theme: jekyll-theme-primer
